# Generated by Django 4.2.20 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partycode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
